/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import data.Conexion;
import data.InquilinoData;
import entities.Inquilino;
import javax.swing.JOptionPane;

/**
 *
 * @author agusv
 */
public class InquilinoView extends javax.swing.JDialog {

    private Inquilino inquilino;
    private InquilinoData inquilinoData;

    /**
     * Creates new form vistaInquilino
     */

    /**
     * Creates new form InquilinoView
     */
    public InquilinoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public InquilinoView(java.awt.Frame parent, boolean modal, Conexion con) {
        super(parent, modal);
        initComponents();
        inquilino = new Inquilino();
        inquilinoData = new InquilinoData(con);
        btnBorrar.setEnabled(false);
        btnActualizar.setEnabled(false);
    }

    public InquilinoView(java.awt.Frame parent, boolean modal, Conexion con, Integer ID) {
        super(parent, modal);
        initComponents();
        inquilino = new Inquilino();
        inquilinoData = new InquilinoData(con);
        obtenerInquilinoXId(ID);
        btnBorrar.setEnabled(false);
        btnActualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalri = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txfGdni = new javax.swing.JTextField();
        lblGdni = new javax.swing.JLabel();
        txfGapellido = new javax.swing.JTextField();
        lblGapellido = new javax.swing.JLabel();
        lblGnombre = new javax.swing.JLabel();
        txfGnombre = new javax.swing.JTextField();
        lblGnombre1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txfDni = new javax.swing.JTextField();
        txfCuit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxActivo = new javax.swing.JCheckBox();
        lblId = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCuit = new javax.swing.JLabel();
        lblTefelono = new javax.swing.JLabel();
        txfId = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        txfTelefono = new javax.swing.JTextField();
        txfApellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnSalri.setText("Salir");
        btnSalri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalriActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));

        lblGdni.setText("Dni Garante");

        lblGapellido.setText("Apellido Garante");

        lblGnombre.setText("Nombre Garante");

        lblGnombre1.setText("GARANTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblGnombre)
                        .addComponent(lblGapellido))
                    .addComponent(lblGdni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfGnombre)
                    .addComponent(txfGapellido)
                    .addComponent(txfGdni, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblGnombre1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGnombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGnombre)
                    .addComponent(txfGnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGapellido)
                    .addComponent(txfGapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfGdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGdni))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));

        txfCuit.setMinimumSize(new java.awt.Dimension(20, 100));

        jLabel11.setText("Estado");

        cbxActivo.setSelected(true);
        cbxActivo.setText("jCheckBox1");

        lblId.setText("Nª Registro");

        lblnombre.setText("Nombre");

        lblApellido.setText("Apellido");

        lblDni.setText("Dni");

        jLabel1.setText("INQUILINO");

        lblCuit.setText("Cuit");

        lblTefelono.setText("Telefono");

        txfId.setMinimumSize(new java.awt.Dimension(20, 100));

        txfNombre.setMinimumSize(new java.awt.Dimension(20, 100));

        txfTelefono.setMinimumSize(new java.awt.Dimension(20, 100));

        txfApellido.setMinimumSize(new java.awt.Dimension(20, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblId)
                                .addComponent(lblTefelono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDni)
                                    .addComponent(lblCuit))
                                .addComponent(lblApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblnombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txfNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfDni, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfCuit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuit)
                    .addComponent(txfCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTefelono)
                    .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbxActivo)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnBorrar)
                .addGap(29, 29, 29)
                .addComponent(btnSalri)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar)
                    .addComponent(btnSalri))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            inquilino.setNombre(txfNombre.getText());
            inquilino.setApellido(txfApellido.getText());
            inquilino.setDni(Long.parseLong(txfDni.getText()));
            inquilino.setCuit(Long.parseLong(txfCuit.getText()));
            inquilino.setTelefono(Long.parseLong(txfTelefono.getText()));
            inquilino.setNombreGarante(txfGnombre.getText());
            inquilino.setApellidoGarante(txfGapellido.getText());
            inquilino.setDniGarante(Long.parseLong(txfGdni.getText()));
            inquilino.setActivo(cbxActivo.isSelected());
            System.out.println("Inquilino: "+inquilino);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al con los datos del inquilino:" + ex);
        }
        try {
            inquilinoData.agregarInquilino(inquilino);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar inquilino:" + ex);
        }
    }// GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txfId.setText("");
        txfNombre.setText("");
        txfApellido.setText("");
        txfDni.setText("");
        txfCuit.setText("");
        txfTelefono.setText("");
        txfGnombre.setText("");
        txfGapellido.setText("");
        txfGdni.setText("");
        btnGuardar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnBorrar.setEnabled(false);
    }// GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {
            inquilino.setId(Integer.parseInt(txfId.getText()));
            inquilino.setNombre(txfNombre.getText());
            inquilino.setApellido(txfApellido.getText());
            inquilino.setDni(Long.parseLong(txfDni.getText()));
            inquilino.setCuit(Long.parseLong(txfCuit.getText()));
            inquilino.setTelefono(Long.parseLong(txfTelefono.getText()));
            inquilino.setNombreGarante(txfGnombre.getText());
            inquilino.setApellidoGarante(txfGapellido.getText());
            inquilino.setDniGarante(Long.parseLong(txfGdni.getText()));
            inquilino.setActivo(cbxActivo.isSelected());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error con los datos al actualizar: " + ex);
        }
        try {
            inquilinoData.modificarInquilino(inquilino);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al tratar de modificar el inquilino:" + ex);
        }
    }// GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txfId.getText());
            inquilinoData.borrarInquilino(id);
        } catch (Exception ex) {

        }
    }// GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalriActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalriActionPerformed
        // TODO add your handling code here:
        dispose();
    }// GEN-LAST:event_btnSalriActionPerformed


    
    private void obtenerInquilinoXId(Integer id) {
        try {
            inquilino = inquilinoData.obtenerInquilinoXId(id);
            txfId.setText(String.valueOf(inquilino.getId()));
            txfId.disable();
            txfNombre.setText(inquilino.getNombre());
            txfApellido.setText(inquilino.getApellido());
            txfDni.setText(String.valueOf(inquilino.getDni()));
            txfCuit.setText(String.valueOf(inquilino.getCuit()));
            txfTelefono.setText(String.valueOf(inquilino.getTelefono()));
            txfGnombre.setText(inquilino.getNombreGarante());
            txfGapellido.setText(inquilino.getApellidoGarante());
            txfGdni.setText(String.valueOf(inquilino.getDniGarante()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Error al obtener inquilino con id:",JOptionPane.WARNING_MESSAGE);            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InquilinoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InquilinoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InquilinoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InquilinoView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InquilinoView dialog = new InquilinoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalri;
    private javax.swing.JCheckBox cbxActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCuit;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblGapellido;
    private javax.swing.JLabel lblGdni;
    private javax.swing.JLabel lblGnombre;
    private javax.swing.JLabel lblGnombre1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTefelono;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextField txfApellido;
    private javax.swing.JTextField txfCuit;
    private javax.swing.JTextField txfDni;
    private javax.swing.JTextField txfGapellido;
    private javax.swing.JTextField txfGdni;
    private javax.swing.JTextField txfGnombre;
    private javax.swing.JTextField txfId;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfTelefono;
    // End of variables declaration//GEN-END:variables
}
