/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.oldView;

import data.Conexion;
import data.InquilinoData;
import entities.Inquilino;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class vistaInquilino extends javax.swing.JInternalFrame {
    private Inquilino inquilino;
    private InquilinoData inquidata;
    /**
     * Creates new form vistaInquilino
     */
    public vistaInquilino(Conexion con) {
        initComponents();
        inquilino=new Inquilino();
        inquidata=new InquilinoData(con);
        btnBorrar.setEnabled(false);
        btnActualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblCuit = new javax.swing.JLabel();
        lblTefelono = new javax.swing.JLabel();
        lblGnombre = new javax.swing.JLabel();
        lblGapellido = new javax.swing.JLabel();
        lblGdni = new javax.swing.JLabel();
        txfId = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        txfApellido = new javax.swing.JTextField();
        txfDni = new javax.swing.JTextField();
        txfCuit = new javax.swing.JTextField();
        txfTelefono = new javax.swing.JTextField();
        txfGnombre = new javax.swing.JTextField();
        txfGapellido = new javax.swing.JTextField();
        txfGdni = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxActivo = new javax.swing.JCheckBox();
        btnBuscarDni = new javax.swing.JButton();
        btnBuscarId = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalri = new javax.swing.JButton();

        jLabel1.setText("Inquilino");

        lblId.setText("Nª Registro");

        lblnombre.setText("Nombre");

        lblApellido.setText("Apellido");

        lblDni.setText("Dni");

        lblCuit.setText("Cuit");

        lblTefelono.setText("Telefono");

        lblGnombre.setText("Nombre Garante");

        lblGapellido.setText("Apellido Garante");

        lblGdni.setText("Dni Garante");

        jLabel11.setText("Estado");

        cbxActivo.setSelected(true);
        cbxActivo.setText("jCheckBox1");

        btnBuscarDni.setText("Buscar");
        btnBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDniActionPerformed(evt);
            }
        });

        btnBuscarId.setText("Buscar");
        btnBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnSalri.setText("Salir");
        btnSalri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalri)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnBorrar)
                        .addGap(134, 134, 134))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblId)
                                .addComponent(lblTefelono, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDni)
                                    .addComponent(lblCuit))
                                .addComponent(lblApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblnombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txfTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfCuit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfNombre)
                                    .addComponent(txfApellido)
                                    .addComponent(txfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscarDni)
                                    .addComponent(btnBuscarId)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblGnombre)
                                        .addComponent(lblGapellido))
                                    .addComponent(lblGdni))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfGnombre)
                                    .addComponent(txfGapellido)
                                    .addComponent(txfGdni, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombre)
                            .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellido)
                            .addComponent(txfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGnombre)
                            .addComponent(txfGnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGapellido)
                            .addComponent(txfGapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfGdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGdni))))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuit)
                    .addComponent(txfCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTefelono)
                    .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbxActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalri)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalriActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalriActionPerformed

    private void btnBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdActionPerformed
        // TODO add your handling code here:
        try{
        inquilino=inquidata.obtenerInquilinoXId(Integer.parseInt(txfId.getText()));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error con el numero de registro" +ex);
        }
        try{
            txfId.setText(String.valueOf(inquilino.getId()));
            txfNombre.setText(inquilino.getNombre());
            txfApellido.setText(inquilino.getApellido());
            txfDni.setText(String.valueOf(inquilino.getDni()));
            txfCuit.setText(String.valueOf(inquilino.getCuit()));
            txfTelefono.setText(String.valueOf(inquilino.getTelefono()));
            txfGnombre.setText(inquilino.getNombreGarante());
            txfGapellido.setText(inquilino.getApellidoGarante());
            txfGdni.setText(String.valueOf(inquilino.getDniGarante()));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error al obtener los datos del inquilino:" +ex);
        }
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnBorrar.setEnabled(true);
    }//GEN-LAST:event_btnBuscarIdActionPerformed

    private void btnBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDniActionPerformed
        // TODO add your handling code here:
        try {
            inquilino=inquidata.obtenerInquilinoXDni(Long.parseLong(txfDni.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error al obtener inquilino con Dni:"+e);
        }
        try{
            txfId.setText(String.valueOf(inquilino.getId()));
            txfNombre.setText(inquilino.getNombre());
            txfApellido.setText(inquilino.getApellido());
            txfDni.setText(String.valueOf(inquilino.getDni()));
            txfCuit.setText(String.valueOf(inquilino.getCuit()));
            txfTelefono.setText(String.valueOf(inquilino.getTelefono()));
            txfGnombre.setText(inquilino.getNombreGarante());
            txfGapellido.setText(inquilino.getApellidoGarante());
            txfGdni.setText(String.valueOf(inquilino.getDniGarante()));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error al obtener los datos del inquilino (por dni):" +ex);
        }
        btnGuardar.setEnabled(false);
        btnActualizar.setEnabled(true);
        btnBorrar.setEnabled(true);
    }//GEN-LAST:event_btnBuscarDniActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
        inquilino.setNombre(txfNombre.getText());
        inquilino.setApellido(txfApellido.getText());
        inquilino.setDni(Long.parseLong(txfDni.getText()));
        inquilino.setCuit(Long.parseLong(txfCuit.getText()));
        inquilino.setTelefono(Long.parseLong(txfTelefono.getText()));
        inquilino.setNombreGarante(txfGnombre.getText());
        inquilino.setApellidoGarante(txfGapellido.getText());
        inquilino.setDniGarante(Long.parseLong(txfGdni.getText()));
        inquilino.setActivo(cbxActivo.isSelected());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al con los datos del inquilino:"+ex);
        }
        try{
        inquidata.agregarInquilino(inquilino);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error al agregar inquilino:"+ ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
            txfId.setText("");
            txfNombre.setText("");
            txfApellido.setText("");
            txfDni.setText("");
            txfCuit.setText("");
            txfTelefono.setText("");
            txfGnombre.setText("");
            txfGapellido.setText("");
            txfGdni.setText("");
            btnGuardar.setEnabled(true);
            btnActualizar.setEnabled(false);
            btnBorrar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try{
        inquilino.setId(Integer.parseInt(txfId.getText()));
        inquilino.setNombre(txfNombre.getText());
        inquilino.setApellido(txfApellido.getText());
        inquilino.setDni(Long.parseLong(txfDni.getText()));
        inquilino.setCuit(Long.parseLong(txfCuit.getText()));
        inquilino.setTelefono(Long.parseLong(txfTelefono.getText()));
        inquilino.setNombreGarante(txfGnombre.getText());
        inquilino.setApellidoGarante(txfGapellido.getText());
        inquilino.setDniGarante(Long.parseLong(txfGdni.getText()));
        inquilino.setActivo(cbxActivo.isSelected());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error con los datos al actualizar: "+ex);
        }
        try{
            inquidata.modificarInquilino(inquilino);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error al tratar de modificar el inquilino:"+ ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        try{
            int id= Integer.parseInt(txfId.getText());
            inquidata.borrarInquilino(id);
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscarDni;
    private javax.swing.JButton btnBuscarId;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalri;
    private javax.swing.JCheckBox cbxActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCuit;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblGapellido;
    private javax.swing.JLabel lblGdni;
    private javax.swing.JLabel lblGnombre;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTefelono;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextField txfApellido;
    private javax.swing.JTextField txfCuit;
    private javax.swing.JTextField txfDni;
    private javax.swing.JTextField txfGapellido;
    private javax.swing.JTextField txfGdni;
    private javax.swing.JTextField txfGnombre;
    private javax.swing.JTextField txfId;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfTelefono;
    // End of variables declaration//GEN-END:variables
}
